server:
  port: 8099

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.110.64:3306/minio-test
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

minio:
  minioUrl: http://192.168.110.64:9000
  assessKey: shZhwRiR0RCaStFIQbZL
  secretKey: oJWoxL4clkqBly33lJ3aJlZ6rj4NMYMTdEEQTqSj
  bucket: minio-test
